services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports: ["8086:8086"]
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin12345
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: sensors
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dev-token
    volumes:
      - influx-data:/var/lib/influxdb2
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports: ["1880:1880"]
    depends_on: [mosquitto, influxdb]
    environment:
      - TZ=America/Detroit
    volumes:
      - nodered-data:/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ["3000:3000"]
    depends_on: [influxdb]
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin12345
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  influx-data:
  nodered-data:
  grafana-data:
